USE uniword;

INSERT INTO words (word, mean, pos, level) VALUES
-- level 1 (초급) - 20개
('ability', '능력', 'noun', 1),
('accept', '받아들이다', 'verb', 1),
('account', '계좌, 계정', 'noun', 1),
('achieve', '달성하다', 'verb', 1),
('apply', '지원하다, 적용하다', 'verb', 1),
('assist', '돕다', 'verb', 1),
('available', '이용 가능한', 'adjective', 1),
('benefit', '혜택, 이익', 'noun', 1),
('cancel', '취소하다', 'verb', 1),
('complete', '완료하다', 'verb', 1),
('confirm', '확인하다', 'verb', 1),
('deadline', '마감일', 'noun', 1),
('deliver', '배달하다', 'verb', 1),
('department', '부서', 'noun', 1),
('effective', '효과적인', 'adjective', 1),
('employee', '직원', 'noun', 1),
('increase', '증가하다', 'verb', 1),
('manage', '관리하다', 'verb', 1),
('meeting', '회의', 'noun', 1),
('require', '요구하다', 'verb', 1),

-- level 2 (중급) - 20개
('accommodate', '수용하다', 'verb', 2),
('acquire', '취득하다', 'verb', 2),
('adjacent', '인접한', 'adjective', 2),
('allocate', '할당하다', 'verb', 2),
('anticipate', '예상하다', 'verb', 2),
('approximately', '대략', 'adverb', 2),
('authorize', '승인하다', 'verb', 2),
('collaborate', '협력하다', 'verb', 2),
('compensate', '보상하다', 'verb', 2),
('comprehensive', '포괄적인', 'adjective', 2),
('consistently', '일관되게', 'adverb', 2),
('consolidate', '통합하다', 'verb', 2),
('constraint', '제약', 'noun', 2),
('deliberate', '의도적인', 'adjective', 2),
('demonstrate', '입증하다', 'verb', 2),
('eligible', '자격이 있는', 'adjective', 2),
('enhance', '향상시키다', 'verb', 2),
('extensive', '광범위한', 'adjective', 2),
('facilitate', '촉진하다', 'verb', 2),
('implement', '시행하다', 'verb', 2),

-- level 3 (고급) - 10개
('amalgamate', '합병하다', 'verb', 3),
('autonomous', '자율적인', 'adjective', 3),
('capitalize', '자본화하다', 'verb', 3),
('contingent', '우발적인', 'adjective', 3),
('depreciate', '가치가 떨어지다', 'verb', 3),
('expedite', '신속히 처리하다', 'verb', 3),
('fluctuate', '변동하다', 'verb', 3),
('incorporate', '통합하다', 'verb', 3),
('procurement', '조달', 'noun', 3),
('remuneration', '보수', 'noun', 3),
('adversely', '불리하게, 반대로', 'adverb', 3),
('commensurate', '상응하는', 'adjective', 3),
('curtail', '축소하다, 삭감하다', 'verb', 3),
('deteriorate', '악화되다', 'verb', 3),
('discrepancy', '불일치, 차이', 'noun', 3),
('imperative', '필수적인', 'adjective', 3),
('intermittent', '간헐적인', 'adjective', 3),
('prevalent', '널리 퍼진', 'adjective', 3),
('provisional', '임시의, 잠정적인', 'adjective', 3),
('stipulate', '규정하다, 명기하다', 'verb', 3);